[package]
name = "ckb-idl-client"
version = "0.1.0"
edition = "2024"
description = "Verification, parsing, and witness encoding for CKB IDL 0.1"
license = "MIT"
repository = "https://github.com/ckb-idl/ckb-idl-client.git"
readme = "README.md"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_path_to_error = "0.1"
serde_json_canonicalizer = "0.3.2"
blake2b_simd = { version = "1" }
hex = { version = "0.4" }
thiserror = { version = "2" }
sha2 = "0.11.0"

[dev-dependencies]
proptest = { version = "1" }
tokio = { version = "1", features = ["rt", "macros"] }
wiremock = { version = "0.6" }
